name: Android Gradle Build and Release

on:
  push:
    tags:
      - 'v*'    # Triggers only on version tags like v1.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Add execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew assembleRelease

      - name: Extract version name and code
        id: get_version
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{ print $2 }' | tr -d '"')
          VERSION_CODE=$(grep 'versionCode' app/build.gradle.kts | awk '{ print $2 }')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ env.VERSION_NAME }}
          body: |
            Version Code: ${{ env.VERSION_CODE }}
            Version Name: ${{ env.VERSION_NAME }}
          artifacts: app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
